on: 
  push:
    branches: main
  workflow_dispatch:
name: Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
  
    - name: Build pages
      run: ./build-pages.sh
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: geospatial.ncsu.edu/geoforall
        username: geoforall@geospatial.ncsu.edu
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        local-dir: build/
        dry-run: false
